import { Press_Start_2P, Fira_Code } from "next/font/google";
import "./globals.css";
import MenuNavBar from "@/components/MenuNavBar";
import Footer from "@/components/Footer";

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.className} ${firaCode.variable} bg-blue text-white`}
      >
        <MenuNavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
