import { Press_Start_2P } from "next/font/google";
import MenuNavBar from "@/components/MenuNavBar";
import "./globals.css";

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.className} bg-blue text-white`}>
        <MenuNavBar />
        {children}
      </body>
    </html>
  );
}
