import {
  SiAxios,
  SiBem,
  SiBootstrap,
  SiCodepen,
  SiCsharp,
  SiCss3,
  SiDevdotto,
  SiDotnet,
  SiEslint,
  SiFigma,
  SiGit,
  SiGithub,
  SiGithubpages,
  SiGmail,
  SiHtml5,
  SiJavascript,
  SiJquery,
  SiLinkedin,
  SiMicrosoftsqlserver,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPrettier,
  SiReact,
  SiReactrouter,
  SiSass,
  SiTailwindcss,
  SiVercel,
  SiVite,
} from "react-icons/si";
import { FaGlobe } from "react-icons/fa6";

const technologyIconCode = {
  "ASP.NET Core": "SiDotnet",
  Axios: "SiAxios",
  "BEM CSS": "SiBem",
  Bootstrap: "SiBootstrap",
  Codepen: "SiCodepen",
  CSS3: "SiCss3",
  "C#": "SiCsharp",
  "Dev.to": "SiDevdotto",
  ESLint: "SiEslint",
  Figma: "SiFigma",
  Git: "SiGit",
  GitHub: "SiGithub",
  "GitHub Pages": "SiGithubpages",
  Gmail: "SiGmail",
  HTML5: "SiHtml5",
  JavaScript: "SiJavascript",
  jQuery: "SiJquery",
  LinkedIn: "SiLinkedin",
  "Next.js": "SiNextdotjs",
  "Node.js": "SiNodedotjs",
  NPM: "SiNpm",
  Prettier: "SiPrettier",
  Preview: "FaGlobe",
  React: "SiReact",
  "React Router": "SiReactrouter",
  SASS: "SiSass",
  SQL: "SiMicrosoftsqlserver",
  "Tailwind CSS": "SiTailwindcss",
  Vercel: "SiVercel",
  Vite: "SiVite",
};

const iconMap = {
  FaGlobe,
  SiAxios,
  SiBem,
  SiBootstrap,
  SiCodepen,
  SiCss3,
  SiCsharp,
  SiDevdotto,
  SiDotnet,
  SiEslint,
  SiFigma,
  SiGit,
  SiGithub,
  SiGithubpages,
  SiGmail,
  SiHtml5,
  SiJavascript,
  SiJquery,
  SiLinkedin,
  SiMicrosoftsqlserver,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPrettier,
  SiReact,
  SiReactrouter,
  SiSass,
  SiTailwindcss,
  SiVercel,
  SiVite,
};

export default function Icon({ iconName }) {
  const iconCode = technologyIconCode[iconName];
  const SelectedIcon = iconMap[iconCode];

  return <SelectedIcon />;
}
